version: '2'
services:
  website:
    container_name: usersapp
    image: usersapp:latest
    ports:
      - 8085:80
  mysql:
     image: mysql:8.0
     container_name: mysql
     command: --default-authentication-plugin=mysql_native_password
     volumes:
       - /tmp/containerization/dockerCompose1/mysql-storage:/var/lib/mysql
     restart: always
     environment:
       - MYSQL_ROOT_PASSWORD=test
       - MYSQL_DATABASE=my_db
       - MYSQL_USER=db_user
       - MYSQL_PASSWORD=db_password
        

